---
cloud_service_group: EC2
cloud_service_type: Instance
name: Total Count
query:
  aggregate:
    - count:
        name: value
options:
  value_options:
    key: value
    options:
      default: 0
